name: anime
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.1.0
  google_sign_in: 5.4.2
  firebase_auth: 4.0.2
  lottie: 1.4.3
  http: 0.13.5
  video_player: 2.4.7
  chewie: 1.3.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true

